// VIEW TAB
export const TAB_CURRENT_POLL = "TAB_CURRENT_POLL";
export const TAB_NEW_POLL = "TAB_NEW_POLL";
export const TAB_YOUR_POLLS = "TAB_YOUR_POLLS";
export const TAB_SIGN_IN = "TAB_SIGN_IN";
export const TAB_SIGN_UP = "TAB_SIGN_UP";

// SETTING TYPE
export const TYPE_INPUT_NUMBER = "TYPE_INPUT_NUMBER";

// ACTIONS - USER
export const ACT_FETCH_USER = "ACT_FETCH_USER";
export const ACT_SIGNING_UP = "ACT_SIGNING_UP";
export const ACT_SIGN_UP_SUCCESSFULLY = "ACT_SIGN_UP_SUCCESSFULLY";
export const ACT_SIGN_UP_UNSUCCESSFULLY = "ACT_SIGN_UP_UNSUCCESSFULLY";
export const ACT_SIGNING_IN = "ACT_SIGNING_IN";
export const ACT_SIGN_IN_SUCCESSFULLY = "ACT_SIGN_IN_SUCCESSFULLY";
export const ACT_SIGN_IN_UNSUCCESSFULLY = "ACT_SIGN_IN_UNSUCCESSFULLY";
export const ACT_SIGN_OUT_USER = "ACT_SIGN_OUT_USER";
export const ACT_CLEAR_AUTH_ERR_MSG = "ACACT_CLEAR_AUTH_ERR_MSGT";

// ACTIONS - POLL
export const ACT_POLL_CREATE = "ACT_POLL_CREATE";
export const ACT_FETCH_POLL_ALL = "ACT_FETCH_POLL_ALL";
export const ACT_FETCH_YOUR_POLLS = "ACT_FETCH_YOUR_POLLS";
