// VIEW TAB
export const TAB_CURRENT_POLL = "TAB_CURRENT_POLL";
export const TAB_NEW_POLL = "TAB_NEW_POLL";
export const TAB_YOUR_POLLS = "TAB_YOUR_POLLS";
export const TAB_SIGN_IN = "TAB_SIGN_IN";
export const TAB_SIGN_UP = "TAB_SIGN_UP";

// SETTING TYPE
export const TYPE_INPUT_NUMBER = "TYPE_INPUT_NUMBER";

// ACTIONS - USER
export const ACT_SIGNING_UP_USER = "ACT_SIGNING_UP_USER";
export const ACT_SIGN_UP_USER = "ACT_SIGN_UP_USER";
export const ACT_SIGNING_IN_USER = "ACT_SIGNING_IN_USER";
export const ACT_SIGN_IN_USER = "ACT_SIGN_IN_USER";
