// VIEW TAB
export const TAB_CURRENT_POLL = "TAB_CURRENT_POLL";
export const TAB_NEW_POLL = "TAB_NEW_POLL";
export const TAB_YOUR_POLLS = "TAB_YOUR_POLLS";

// SETTING TYPE
export const TYPE_INPUT_NUMBER = "TYPE_INPUT_NUMBER";
